### ISSUE TITLE
Optionally lint Title + Body

### ISSUE THREAD

**Issue by melink14** [dreampulse/action-lint-pull-request-title#34]
Thanks for making this useful action!

For squash and merge with one commit, Github uses title + description as commit message. Since commitlint also has restrictions on the body it'd be good to lint that too.

it seems it would just be a simple append in your current script but let me know what you think!

**Comment by dreampulse** [comment]
You mean you would lint the body / description of the PR message?

What would be a useful linting rule for the description?

**Comment by dreampulse** [comment]
@melink14 we could pass that as an additional option. Are you working on this?

```
name: "Lint PR Title"
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: dreampulse/action-lint-pull-request-title@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINT_BODY: true. # <---- new
```
